on:
  issues:
    types: [opened]

jobs:
  manage-registry:
    runs-on: ubuntu-latest
    name: Maintain the device registry via issues
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run maintainance action
        uses: ./action