on:
  issues:
    types: [opened]

jobs:
  manage-registry:
    runs-on: ubuntu-latest
    name: Maintain the device registry via issues
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        working-directory: ./action
        with:
          node-version: "12"
          cache: "npm"
      - name: Install dependencies
        run: npm install
        working-directory: ./action
      - name: Run maintainance action
        uses: ./action